project_id = "hwezwdzxnvbwnjkrwucw"

[functions.approve-admin-request]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.test-cj-api]
verify_jwt = false

[functions.cj-my-products]
verify_jwt = false

[functions.cj-product-cost]
verify_jwt = false

[functions.sync-cj-costs]
verify_jwt = false

[functions.cj-freight]
verify_jwt = false
